container-name-run : "python-flask-run"
container-name-tools : "python-flask-tools"

host-path-run : "."
host-path-tools : "."

container-path-run : "/app"
container-path-tools : "/app"

container-port-map : "8000:8000"
container-port-map-debug : "5858:5858"

dockerfile-run : "Dockerfile"
dockerfile-tools : "Dockerfile-tools"

image-name-run : "python-flask-run"
image-name-tools : "python-flask-tools"

build-cmd-run : "npm install --production --unsafe-perm"
test-cmd : "python -m tests.app_tests"
build-cmd-debug : "python -m compileall"

run-cmd : ""
debug-cmd : "flask run"
stop-cmd : ""
