from python:2-alpine

ENV FLASK_APP server
ENV FLASK_DEBUG true

COPY . /usr/app

COPY requirements.txt /tmp/requirements.txt
RUN cd /tmp && pip install -r requirements.txt

WORKDIR /usr/app

CMD ["flask", "run"]